## Tensorflow Tensor Fundamental

- *Tensorflow is an open-source end-to-end machine learning library for preprocessing data, modeling data and serving, models, (getting them into the hands of others)*

In [20]:
import tensorflow as tf

print(tf.__version__)

2.17.0


***

## Tensor

- *Tensor is kinda a friend of array numpy, but instead it's living in GPU not CPU*

### *Scalar (0-dimensional tensor)*

In [21]:
tensor_scalar = tf.constant(16)
tensor_scalar

<tf.Tensor: shape=(), dtype=int32, numpy=16>

#### Check the dimension of tensor

In [22]:
tensor_scalar.ndim

0

### *Vector (1-dimensional tensor)*

In [23]:
vector = tf.constant([16,10,2004])
vector

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([  16,   10, 2004], dtype=int32)>

In [24]:
vector.ndim

1

### *Matrix (2-dimensional tensor)*

In [25]:
TENSOR_MATRIX = tf.constant([[16,10,2004],
                             [17,10,2004.0]], dtype=tf.float32)


TENSOR_MATRIX

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[  16.,   10., 2004.],
       [  17.,   10., 2004.]], dtype=float32)>

#### Check dimensional of matrix

In [26]:
TENSOR_MATRIX.ndim

2

#### Check the shape of the matrix

In [27]:
TENSOR_MATRIX.shape

TensorShape([2, 3])

### *Tensor (multiple-dimensional tensor)*

- *All of those scalar, vector, matrix above are also technically tensor*

In [28]:
tensor = tf.constant([[[[16,10,2004],
                       [9,3,1986],
                       [4,1,2004]]]])
tensor

<tf.Tensor: shape=(1, 1, 3, 3), dtype=int32, numpy=
array([[[[  16,   10, 2004],
         [   9,    3, 1986],
         [   4,    1, 2004]]]], dtype=int32)>

#### Dimension

- *Number of bracket that tensor have*

In [29]:
tensor.ndim

4

#### Shape

- *Shape: The length (number of elements) of each of the dimensions of a tensor.*


In [30]:
tensor.shape

TensorShape([1, 1, 3, 3])

#### Size

- *Size: The total number of items in the tensor.*

In [31]:
tf.size(tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=9>

#### Rank

- *Rank: The number of tensor dimensions. A scalar has rank 0, a vector has rank 1, a matrix is rank 2, a tensor has rank n.*

In [32]:
tf.rank(tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=4>

***
### *tf.constant & tf.Variable*

- *The differences between tf.constant() and tf.Variable() is tensors created with tf.constant() are immutable, whereas tensors created with tf.Variable() are mutable*

In [33]:
mutable_tensor = tf.Variable([16,10,2004])
immutable_tensor = tf.constant([17,10,2004])

mutable_tensor

<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([  16,   10, 2004], dtype=int32)>

#### Assign item functionally

In [34]:
# mutable_tensor[0] = 15

#### Mutable tensor

- *Change tensor items by using its built-in func*

In [35]:
mutable_tensor[0].assign(15)
mutable_tensor

<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([  15,   10, 2004], dtype=int32)>

#### Immutable tensor

In [36]:
# immutable_tensor[0].assign(15)


***
## Random Tensor

In [37]:
seed = 16       # set the seed for reproducibility

ran_generator = tf.random.Generator.from_seed(seed)
ran_tensor = ran_generator.normal(shape=(16,10))                # Create tensor from normal distribution
ran_tensor[0]



<tf.Tensor: shape=(10,), dtype=float32, numpy=
array([-0.63509274,  0.3703566 , -1.0939722 , -0.46014452,  1.5420506 ,
       -0.16822556, -0.43908644, -0.41292423,  0.35877243, -1.9095894 ],
      dtype=float32)>

### *Shuffle tensor (without seed)*

In [38]:
shuffled_tensor = tf.random.shuffle(ran_tensor)
shuffled_tensor[0:2]

<tf.Tensor: shape=(2, 10), dtype=float32, numpy=
array([[ 0.959224  ,  0.85874265, -1.518177  ,  1.4020647 ,  1.5570306 ,
        -0.96762174,  0.49529105, -0.648484  , -1.8700892 ,  2.7830641 ],
       [-2.3001142 , -1.349454  ,  0.81485   ,  1.2790666 ,  0.02203509,
         1.5428121 ,  0.78953624,  0.53897345, -0.48535708,  0.74055266]],
      dtype=float32)>

### *Shuffle tensor (with seed)*

- *No difference al all*

- *Why?, It's due to the rule#4 of set radom seed (global level and operation level)*

- *Rule#4: If both the global and operation seed are set: Both seeds are used in conjunction to determine the random sequence.*

- *And we not set the global seed later then*

In [39]:
shuffled_tensor = tf.random.shuffle(ran_tensor, seed=16)
shuffled_tensor[0:2]

<tf.Tensor: shape=(2, 10), dtype=float32, numpy=
array([[-2.3001142 , -1.349454  ,  0.81485   ,  1.2790666 ,  0.02203509,
         1.5428121 ,  0.78953624,  0.53897345, -0.48535708,  0.74055266],
       [ 0.09988727, -0.50998646, -0.7535806 , -0.5716629 ,  0.1480774 ,
        -0.23362991, -0.3522796 ,  0.40621266, -1.0523509 ,  1.2054597 ]],
      dtype=float32)>

### *Set global seed*

- *How?*

- **tf.random.set_seed(10)** : *Set the global seed*

- **tf.random.shuffle(..., seed=10)** : *Set the operation seed*

- *Because, "Operation that rely on a random  seed actually derive it from two seeds: the global and operation-level seeds. This make the predictable random sequence"*

In [40]:
tf.random.set_seed(2004)                                    # ! Set the global random seed

shuffled_tensor = tf.random.shuffle(ran_tensor, seed=10)    # ! Set the operation-level seed
shuffled_tensor[0:2]



<tf.Tensor: shape=(2, 10), dtype=float32, numpy=
array([[-1.0345329 ,  1.3066901 , -1.5184573 , -0.4585211 ,  0.5714663 ,
        -1.5331722 ,  0.45331386,  1.1487608 , -1.2659091 , -0.47450137],
       [ 0.959224  ,  0.85874265, -1.518177  ,  1.4020647 ,  1.5570306 ,
        -0.96762174,  0.49529105, -0.648484  , -1.8700892 ,  2.7830641 ]],
      dtype=float32)>

In [41]:
shuffled_tensor = tf.random.shuffle(ran_tensor)
shuffled_tensor[0:2]

<tf.Tensor: shape=(2, 10), dtype=float32, numpy=
array([[ 0.18706241,  0.66179603,  0.01380118, -0.24827152,  1.2111493 ,
        -0.7199124 , -0.04082382,  2.6791053 ,  1.0914805 ,  0.33149612],
       [-0.63509274,  0.3703566 , -1.0939722 , -0.46014452,  1.5420506 ,
        -0.16822556, -0.43908644, -0.41292423,  0.35877243, -1.9095894 ]],
      dtype=float32)>

***

## Zeros and Ones

In [42]:
zeros_tensor = tf.zeros(shape=([16]))
zeros_tensor

<tf.Tensor: shape=(16,), dtype=float32, numpy=
array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
      dtype=float32)>

In [43]:
ones_tensor = tf.ones(shape=(1,16))
ones_tensor

<tf.Tensor: shape=(1, 16), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]],
      dtype=float32)>

## Zeros_like & Ones_likes

- *Turn any tensor into zeros or ones tensor*

In [44]:
zeros_like_tensor = tf.zeros_like(tensor)
zeros_like_tensor



<tf.Tensor: shape=(1, 1, 3, 3), dtype=int32, numpy=
array([[[[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]]]], dtype=int32)>

In [45]:
ones_like_tensor = tf.ones_like(tensor, dtype=tf.float32)
ones_like_tensor

<tf.Tensor: shape=(1, 1, 3, 3), dtype=float32, numpy=
array([[[[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]]], dtype=float32)>

## Tensor within a range

In [46]:
range_tensor = tf.range(2,100, 3)
range_tensor

<tf.Tensor: shape=(33,), dtype=int32, numpy=
array([ 2,  5,  8, 11, 14, 17, 20, 23, 26, 29, 32, 35, 38, 41, 44, 47, 50,
       53, 56, 59, 62, 65, 68, 71, 74, 77, 80, 83, 86, 89, 92, 95, 98],
      dtype=int32)>

***
## Manipulating Tensor (Operations)

- *Scalar Operations (addition, subtraction, division, multiplication)*

- *Matrix Operations*

### *Matrix multiplication*

Rules for matrix multiplication

1. The inner dimensions must match:

        (3, 5) @ (3, 5) won't work
        (5, 3) @ (3, 5) will work
        (3, 5) @ (5, 3) will work

2. The resulting matrix has the shape of the outer dimensions:

        (5, 3) @ (3, 5) -> (5, 5)
        (3, 5) @ (5, 3) -> (3, 3)


*🔑 Note: '@' in Python is the symbol for matrix multiplication.*

Other way to perform matrix multiplication:
- **torch.matmul()**
- **Tensor.matmul()**

*Matrix multiplication like this is also referred to as the **dot product** of two matrices*



In [47]:
tensor_16x10 = ran_generator.normal(shape=(16,10))
tensor_10x16 = ran_generator.normal(shape=(10,16))


#### Using built-in tf.matmul(..,...) func

In [106]:
# (16,10) @ (10, 16) -> (16,16)
tensor_16x16 = tf.matmul(tensor_16x10, tensor_10x16)
tensor_16x16

<tf.Tensor: shape=(16, 16), dtype=float32, numpy=
array([[ 4.2038293 , -3.972705  ,  1.4909074 ,  4.44551   ,  2.0857296 ,
        -4.7100725 , -1.0329397 ,  1.8675054 ,  3.4897459 , -0.7453317 ,
         1.4956397 ,  0.40196013, -3.3873055 , -3.412331  , -2.0619242 ,
         0.47847193],
       [-4.553067  , -1.3557166 , -1.4219984 , -5.2959957 , -0.73925716,
         0.66965055,  4.0238295 , -1.4578154 , -2.6669    , -0.7636551 ,
        -1.0731478 , -4.705254  ,  1.1987076 ,  2.6519995 ,  4.7364674 ,
        -4.1269283 ],
       [-8.181668  , -0.5916847 ,  4.165633  , -7.31096   ,  2.977646  ,
         4.3029566 ,  1.7791419 , -2.3690608 , -0.7356029 ,  0.10256758,
         6.3211026 ,  4.843779  , -6.93559   , -3.8951476 ,  2.5149715 ,
         0.09122634],
       [ 6.541566  ,  1.7434082 ,  0.44736147,  2.3959453 , -3.3165853 ,
         1.303717  , -1.2798717 ,  1.7798505 ,  1.3120034 ,  5.947422  ,
        -5.8956766 , -0.723768  ,  5.0983133 , -7.0033283 ,  4.5914655 ,
        

#### Using built-in tf.tensordot()

In [105]:
tf.tensordot(tensor_16x10, tensor_10x16, axes=1)

<tf.Tensor: shape=(16, 16), dtype=float32, numpy=
array([[ 4.2038293 , -3.972705  ,  1.4909074 ,  4.44551   ,  2.0857296 ,
        -4.7100725 , -1.0329397 ,  1.8675054 ,  3.4897459 , -0.7453317 ,
         1.4956397 ,  0.40196013, -3.3873055 , -3.412331  , -2.0619242 ,
         0.47847193],
       [-4.553067  , -1.3557166 , -1.4219984 , -5.2959957 , -0.73925716,
         0.66965055,  4.0238295 , -1.4578154 , -2.6669    , -0.7636551 ,
        -1.0731478 , -4.705254  ,  1.1987076 ,  2.6519995 ,  4.7364674 ,
        -4.1269283 ],
       [-8.181668  , -0.5916847 ,  4.165633  , -7.31096   ,  2.977646  ,
         4.3029566 ,  1.7791419 , -2.3690608 , -0.7356029 ,  0.10256758,
         6.3211026 ,  4.843779  , -6.93559   , -3.8951476 ,  2.5149715 ,
         0.09122634],
       [ 6.541566  ,  1.7434082 ,  0.44736147,  2.3959453 , -3.3165853 ,
         1.303717  , -1.2798717 ,  1.7798505 ,  1.3120034 ,  5.947422  ,
        -5.8956766 , -0.723768  ,  5.0983133 , -7.0033283 ,  4.5914655 ,
        

#### Using python matrix multiplication operator

In [49]:
# (16,10) @ (10, 16) -> (16,16)
tensor_16x16 = tensor_16x10 @ tensor_10x16
tensor_16x16.shape

TensorShape([16, 16])

In [50]:
# (10,16) @ (16, 10) -> (10,10)
tensor_10x10 = tensor_10x16 @ tensor_16x10 
tensor_10x10.shape

TensorShape([10, 10])

#### Mismatching shape

- *Trying to matrix multiply two tensors with the shape (16, 16) and (10,10) errors because the inner dimensions don't match.*

In [54]:
# tensor_16x16 @ tensor_10x10       # -> Error


### *Element-wise multiplication*

-  Suppose **s** and **t** are two vectors of the **same dimension**. Then we use **s ⊙ t** to denote the element-wise product of the two vectors. 

        [1 2] ⊙ [3 4] = [1x3  2x4] = [3 8]      -> Mathematical Notation 
        [1 2] * [3 4] = [1x3  2x4] = [3 8]      -> Programming Syntax

*Element-wise multiplication is sometimes called the **Hadamard product** or **Schur product**, applied the same rule as matrix Addition, Subtraction*

*This rule of same size applied for all kind of tensor*

**Element-wise multiplication != Matrix multiplication**

*Stay caffeinated*

In [57]:
tensor

<tf.Tensor: shape=(1, 1, 3, 3), dtype=int32, numpy=
array([[[[  16,   10, 2004],
         [   9,    3, 1986],
         [   4,    1, 2004]]]], dtype=int32)>

In [58]:
tensor * tensor


<tf.Tensor: shape=(1, 1, 3, 3), dtype=int32, numpy=
array([[[[    256,     100, 4016016],
         [     81,       9, 3944196],
         [     16,       1, 4016016]]]], dtype=int32)>

### *Matrix addition, Subtraction, Division*

**Rule**

-   *The matrices are using for these kind of operators must be the same size (shape)*

The rule are also applied for Matrices Subtraction, Addition, Division also

In [61]:
tensor + tensor

<tf.Tensor: shape=(1, 1, 3, 3), dtype=int32, numpy=
array([[[[  32,   20, 4008],
         [  18,    6, 3972],
         [   8,    2, 4008]]]], dtype=int32)>

***

## Transpose matrix

### *0-dimensional tensor transpose is deprecated*

### *1-dimensional tensor*

In [62]:
vector

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([  16,   10, 2004], dtype=int32)>

In [65]:
tf.transpose(vector)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([  16,   10, 2004], dtype=int32)>

### *2-dimensional tensor*

In [69]:
TENSOR_MATRIX

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[  16.,   10., 2004.],
       [  17.,   10., 2004.]], dtype=float32)>

In [68]:
tf.transpose(TENSOR_MATRIX)

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[  16.,   17.],
       [  10.,   10.],
       [2004., 2004.]], dtype=float32)>

### *3-dimensional tensor*

**I got it:**

- *transpose mean that you indirectly reshape the matrix or the tensor, but in a simple way, that you just rearrange or swap the dimension of a tensor without redefine, that's it*

        tensor.transpose(0,1) => swap the 0th dim to the 1th dim => 
        tensor.transpose(0,2) => swap the 0th dim to the 2th dim => tensor.T    (short-hand syntax)
        tensor.transpose(1,2) => swap the 1th dim to the 2th dim => tensor.mT 

*There're much more things to play when we deal with higher multi-dimensional tensors, stay tuned*

In [92]:
tensor = ran_generator.normal(shape=(3,4,5))
tensor

<tf.Tensor: shape=(3, 4, 5), dtype=float32, numpy=
array([[[-1.36147153e+00, -2.33377159e-01, -2.28903580e+00,
          9.93328989e-02,  3.15539688e-01],
        [ 1.04535581e-03,  5.71016848e-01,  1.03863835e+00,
         -1.53552532e-01, -6.78686440e-01],
        [ 1.21322966e+00, -3.41942906e-01,  1.23073947e+00,
          9.98039961e-01,  1.21679735e+00],
        [-1.27996218e+00,  3.57582390e-01, -6.28156513e-02,
          2.63933444e+00,  6.26899004e-01]],

       [[-7.67167449e-01,  9.24597621e-01, -1.93849206e+00,
         -1.57898709e-01, -1.04575431e+00],
        [-1.52267671e+00, -5.60429394e-01, -2.87943203e-02,
         -5.75450361e-01,  6.66985452e-01],
        [-2.95351446e-01,  2.36252218e-01,  3.06836069e-01,
          2.21696403e-02, -4.53152269e-01],
        [-1.03087842e+00,  9.21760499e-01,  1.37657726e+00,
         -3.12642217e-01, -1.29235482e+00]],

       [[-5.56336977e-02, -2.86156356e-01,  6.93222225e-01,
          1.65933144e+00, -9.58449185e-01],
        [

In [99]:
tf.transpose(tensor, perm=[1,2,0])

<tf.Tensor: shape=(4, 5, 3), dtype=float32, numpy=
array([[[-1.36147153e+00, -7.67167449e-01, -5.56336977e-02],
        [-2.33377159e-01,  9.24597621e-01, -2.86156356e-01],
        [-2.28903580e+00, -1.93849206e+00,  6.93222225e-01],
        [ 9.93328989e-02, -1.57898709e-01,  1.65933144e+00],
        [ 3.15539688e-01, -1.04575431e+00, -9.58449185e-01]],

       [[ 1.04535581e-03, -1.52267671e+00, -1.20679367e+00],
        [ 5.71016848e-01, -5.60429394e-01,  3.05994928e-01],
        [ 1.03863835e+00, -2.87943203e-02, -6.47587836e-01],
        [-1.53552532e-01, -5.75450361e-01,  8.33121717e-01],
        [-6.78686440e-01,  6.66985452e-01, -1.17937535e-01]],

       [[ 1.21322966e+00, -2.95351446e-01,  6.99419081e-02],
        [-3.41942906e-01,  2.36252218e-01, -1.86203647e+00],
        [ 1.23073947e+00,  3.06836069e-01,  1.37871695e+00],
        [ 9.98039961e-01,  2.21696403e-02, -1.38956165e+00],
        [ 1.21679735e+00, -4.53152269e-01, -7.27138638e-01]],

       [[-1.27996218e+00, -1

***
## Reshape

- *Reshape is like you redefine the shape of the tensor as long as the product of all size not change*

- *Love the way you like, I'm not that young naive anymore*

        (3,4,5) => total element : 3 * 4 * 5 = 60

- *Can be reshape into:*

        (3,5,4) => total elements : 3 * 5 * 4 = 60 (transposed)

        (6, 10) => total elements : 6 * 10 = 60 (properly reshape)
        (30, 2) => total elements : 30 * 2 = 60 (properly reshape)


        

In [100]:
tensor

<tf.Tensor: shape=(3, 4, 5), dtype=float32, numpy=
array([[[-1.36147153e+00, -2.33377159e-01, -2.28903580e+00,
          9.93328989e-02,  3.15539688e-01],
        [ 1.04535581e-03,  5.71016848e-01,  1.03863835e+00,
         -1.53552532e-01, -6.78686440e-01],
        [ 1.21322966e+00, -3.41942906e-01,  1.23073947e+00,
          9.98039961e-01,  1.21679735e+00],
        [-1.27996218e+00,  3.57582390e-01, -6.28156513e-02,
          2.63933444e+00,  6.26899004e-01]],

       [[-7.67167449e-01,  9.24597621e-01, -1.93849206e+00,
         -1.57898709e-01, -1.04575431e+00],
        [-1.52267671e+00, -5.60429394e-01, -2.87943203e-02,
         -5.75450361e-01,  6.66985452e-01],
        [-2.95351446e-01,  2.36252218e-01,  3.06836069e-01,
          2.21696403e-02, -4.53152269e-01],
        [-1.03087842e+00,  9.21760499e-01,  1.37657726e+00,
         -3.12642217e-01, -1.29235482e+00]],

       [[-5.56336977e-02, -2.86156356e-01,  6.93222225e-01,
          1.65933144e+00, -9.58449185e-01],
        [

In [102]:
tf.reshape(tensor, shape=(12,5))

<tf.Tensor: shape=(12, 5), dtype=float32, numpy=
array([[-1.36147153e+00, -2.33377159e-01, -2.28903580e+00,
         9.93328989e-02,  3.15539688e-01],
       [ 1.04535581e-03,  5.71016848e-01,  1.03863835e+00,
        -1.53552532e-01, -6.78686440e-01],
       [ 1.21322966e+00, -3.41942906e-01,  1.23073947e+00,
         9.98039961e-01,  1.21679735e+00],
       [-1.27996218e+00,  3.57582390e-01, -6.28156513e-02,
         2.63933444e+00,  6.26899004e-01],
       [-7.67167449e-01,  9.24597621e-01, -1.93849206e+00,
        -1.57898709e-01, -1.04575431e+00],
       [-1.52267671e+00, -5.60429394e-01, -2.87943203e-02,
        -5.75450361e-01,  6.66985452e-01],
       [-2.95351446e-01,  2.36252218e-01,  3.06836069e-01,
         2.21696403e-02, -4.53152269e-01],
       [-1.03087842e+00,  9.21760499e-01,  1.37657726e+00,
        -3.12642217e-01, -1.29235482e+00],
       [-5.56336977e-02, -2.86156356e-01,  6.93222225e-01,
         1.65933144e+00, -9.58449185e-01],
       [-1.20679367e+00,  3.05994

***
## One-hot encoding

In [113]:
tf.one_hot([16,10,2004], depth=4)

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>